

const Sneakers = [
    {
      id: "adidas-1",
      name: "Adidas Ultraboost 22",
      price: 180,
      currency: "$",
      gender: "male",
      image: "../src/assets/images/male-imgfolder/adidas-m1.png",
      category: "running",
      brand: "adidas",
      imageThumbnails: [
        'side', 'front'
      ]
    },
    {
      id: "adidas-2",
      name: "Adidas Forum Low",
      price: 120,
      gender: "male",
      image: "../src/assets/images/male-imgfolder/adidas-m2.png",
      category: "lifestyle",
      brand: "adidas",
    },
    {
      id: "adidas-3",
      name: "Adidas Samba",
      price: 160,
      gender: "female",
      image: "../src/assets/images/female-imgfolder/adidas-1f.png",
      category: "casual",
      brand: "adidas",
    },
     {
      id: "adidas-4",
      name: "Adidas boost",
      price: 145,
      gender: "female",
      image: "../src/assets/images/female-imgfolder/adidas-2f.png",
      category: "casual",
      brand: "adidas",
    },
    {
      id: "jordan-1",
      name: "Air Jordan 1 Retro High",
      price: 200,
      gender: "male",
      image: "../src/assets/images/male-imgfolder/male-jordans1.png",
      category: "basketball",
      brand: "jordans",
    },
    {
      id: "jordan-2",
      name: "Air Jordan 4 Retro",
      price: 220,
      gender: "male",
      image: "../src/assets/images/male-imgfolder/male-jordans2.png",
      category: "basketball",
      brand: "jordans",
    },
    {
      id: "jordan-3",
      name: "Jordan Delta",
      price: 170,
      gender: "female",
      image: "../src/assets/images/female-imgfolder/jordans-f2.png",
      category: "lifestyle",
      brand: "jordans",
    },
    {
      id: "jordan-4",
      name: "Jordan pinky",
      price: 160,
      gender: "female",
      image: "../src/assets/images/female-imgfolder/jordans-f1.png",
      category: "lifestyle",
      brand: "jordans",
    },
    {
      id: "airforce-1",
      name: "Nike Air Force 1 Low",
      price: 150,
      gender: "female",
      image: "../src/assets/images/female-imgfolder/nike-f1.png",
      category: "lifestyle",
      brand: "nikeAirforce",
    },
    {
      id: "airforce-2",
      name: "Nike Air Force 1 '07",
      price: 155,
      gender: "male",
      image: "../src/assets/images/male-imgfolder/nike-m1.png",
      category: "lifestyle",
      brand: "nikeAirforce",
    },
    {
      id: "airforce-3",
      name: "Nike Pegasus",
      price: 140,
      gender: "male",
      image: "../src/assets/images/male-imgfolder/nike-m2.png",
      category: "casual",
      brand: "nikeAirforce",
    },
     {
      id: "airforce-4",
      name: "Nike Air Force 1 '09",
      price: 140,
      gender: "female",
      image: "../src/assets/images/female-imgfolder/nike-f2.png",
      category: "casual",
      brand: "nikeAirforce",
    },
];

export default Sneakers;

